APP_NAME: "gRPCDemo"
APP_PORT: "33001"

# MongoDB URI
#DB_URI: "mongodb://user:password@localhost:27017/dbname?authMechanism=SCRAM-SHA-1"
#DB_NAME: "dbname"

# Postgres
DB_URI: "postgresql://postgres:root@localhost:5432/grpc_test?sslmode=disable"
